### PR TITLE
Quite significant boost

### PR DESCRIPTION
**Pull request by sirex**
Not sure if there are any chances for you to accept these changes, but still letting you know what I did.

Here are the list of changes:
- Upgraded Django from 1.5 to 1.9.
- Changed url path to template mapping from `/path/ -> templates/prototype/path/index.html` to `/path/ -> templates/path.html`. `templates/path/index.html` still works, but is not enforced.
- Added `prototype.yml` file to make it possible to provide context to templates.
- Added support for Django static files with `static` template tag.
- Added support for `url` template tag with named urls.
- Added build-in support for python-livereload.
- Added build-in support for libsass.

Let me know if you willing to accept this, then I will fix failing tests. If not, I will create a fork with different name.

### CODE REVIEW

**Comment by goodtune** [comment]
Thanks so much for this, it is quite an exhaustive set of changes!

I will give it a review and provide some feedback - I like the general gist of what you've got here though.

**Comment by goodtune** [comment]
I'm not convinced there is an advantage of maintaining `prototype.yml` over the regular Django process of updating the `urls.py` file? It also introduces a dependency on `PyYAML`. What is the rationale for this approach?

Also what are the advantages of the `prototype` command over the `runserver` management command and adding `livereload` as a dependency?

I think that my existing implementation has done a disservice here - I've mixed the test suite too heavily with the reusable application (ie. I should not have a `settings.py` file in the app directory, it should have been a standalone test project).

**Comment by sirex** [comment]
In my case I was looking for tool to quickly create web site prototypes and in my case these prototypes would be written by a frontender who does not know anything about Django or Python. When prototype is finished, I wanted to move all templates to a Django project and then define urls and views.

In order to define urls in `urls.py` file, first you need to create a working Django project. And person who is working on this (in my case a frontender) would need to know regular expressions and how to define Django urls and map those to template view with context.

I wanted to make it as simple as possible, to just create working Django templates that can be later moved to the Django project. What you described does not require `django-prototype` at all, because you can just create new Django project `django-admin createproject myprototype` and start working on templates, defining urls with context like this:

``` python
urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="index.html", context={}), name='index'),
]
```

What I did, is a simple wrapper around all Django complexities:

``` yaml
urls:
  /:
    name: index
    context: {}
```

livereload comes very handy when you write html and css. Usually designers and frontenders have two monitors, one monitor for writing html/css other for looking at the results in browsers. With livereload you only need to save edited file and changes will be automatically show on browser.

Since working on prototypes mostly involves only html/css code, so livereload is quite handy.

Also, I see django-prototype not as a library, but as a standalone project. For example:

```
$ pip install django-prototype
$ prototype init
$ prototype run
```

And that's it, you can start prototyping by writing templates with stub contexts defined in nice yaml file.

**Comment by goodtune** [comment]
You are right about that, the existing implementation is little more than a loose wrapper around `TemplateView`.

I like your use case, it is different to mine but I see the benefits.

**Comment by goodtune** [comment]
Different project goals, feel free to fork this - I will update (add) a permissive license.

**Pull request closed without merging**
